version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env

  bot:
    build: .
    container_name: phoenix_bot
    depends_on:
      - db
    env_file:
      - .env